### ISSUE TITLE
Official CPS 3.1.0 still has crash bug with Admit Criteria CTCSS/DCS switching from Analog to Digital channel

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/radioddity_gd-77_cps2.0.5#48]
This bug is for @lxa520 official CPS

Steps to reproduce..

Make new Digital channel
Make new Analog channel

Open Analog channel and set Admit Criteria to CTCSS/DCS

Press arrow key (back arrow) to open previous Digital Channel (digital channel is shown)
Press arrow key (forward arrow) to open Analog channel

CPS crashes

This is because TxTone is set to "None" when form loads, and the Admit Criteria combobox removes option for CTCSS/DCS if TxTone is "None".

See my commit

https://github.com/rogerclarkmelbourne/radioddity_gd-77_cps2.0.5/commit/28ec57b4d259ac61294cda5751c79514d9a86813#diff-ee461f48f7483798e819e757d960910a

This reads data for Channel and uses this data (of TxTone) rather than reading value of TxTone ComboBox, which is not initialised when Admit Criteria Combobox is initialized

************** Exception Text **************
System.ArgumentOutOfRangeException: InvalidArgument=Value of '2' is not valid for 'SelectedIndex'.
Parameter name: SelectedIndex
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at DMR.ChannelForm.DispData()
   at DMR.ChannelForm.DhfrzZ2oQr(Object  , EventArgs  )
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by lxa520** [comment]
OK, i get it. 
next version, i will fixed it. 
thank you very much

**Comment by rogerclarkmelbourne** [comment]
OK.

No problem

**Comment by lxa520** [comment]
i move code  after set tx tone;

  // thie code must after tx tone
  RefreshAdmitCriteria();
  cmbAdmitCriteria.SelectedIndex = one.AdmitCriteria;

**Comment by rogerclarkmelbourne** [comment]
OK

Same result.
